### PR TITLE
Only load Kapnismology engine when Rails is defined

### PR DESCRIPTION
**Pull request by ssteeg-mdsol**
Aside from whitespace changes, wrapping engine.rb in `if defined?(Rails)` is the only real change.

@ykitamura-mdsol @JordiPolo @jfeltesse-mdsol

### CODE REVIEW

**Comment by jcarres-mdsol** [comment]
I think gemspec still says the gem depends on rails
should be development dependency, also figure out how to run specs without loading rails so we make sure there is nothing in the code depending on rails methods (I think there is nothing but just in case)

**Comment by ssteeg-mdsol** [comment]
Updated and Travis builds are all passing now 😅

**Comment by ykitamura-mdsol** [comment]
looks friendly to me 👍

**Comment by jfeltesse-mdsol** [comment]
💯

**Comment by jcarres-mdsol** [comment]
merging 🐐

**Pull request merged**
