### PR TITLE
output has version information

### PR DESCRIPTION
**Pull request by jcarres-mdsol**
because versions are cool @jfeltesse-mdsol @ykitamura-mdsol

### CODE REVIEW

**Comment by jfeltesse-mdsol** [comment]
the people wants a sample output :metal:

**Comment by jcarres-mdsol** [comment]
screen shot 2016-08-12 at 2 38 49 pm

**Comment by ykitamura-mdsol** [comment]
looks good to me 👍 

Are we going to have server IP address also?

**Comment by jcarres-mdsol** [comment]
need to ask people in .net if they can do it easily , can come in a different PR

**Comment by ykitamura-mdsol** [comment]
:ok:

**Comment by jfeltesse-mdsol** [comment]
LGTM but wouldn't there be a more appropriate word than "version"? I'd expect something like "v1.0.0" when talking about "version"...
for instance "revision" or "ref" or "commit" or else..?

**Comment by jcarres-mdsol** [comment]
Changed version to codebase_revision @jfeltesse-mdsol  @ykitamura-mdsol

**Comment by jfeltesse-mdsol** [comment]
👍

**Pull request merged**
